### ISSUE TITLE
Avoid NullPointerException when properties are not set

### ISSUE THREAD

**Issue by Nheverest** [seedstack/mqtt-addon#12]
Seedstack application startup fails with hardly usable logs when any _vendorProperties_ is configured without value. 

Example (see brokerURL below):
```
jms:
  connectionFactories:
    appActiveMQConnectionFactory:
      vendorClass: org.apache.activemq.ActiveMQConnectionFactory
      vendorProperties:
        brokerURL: 

```
Purpose of this ticket is to avoid NullPointerException (e.g. using HashMap instead of Properties in JmsConfig), or to provide developers with a more explicit error message.

**Comment by adrienlauer** [comment]
Done in Coffig 3.1.6
